# Generated by Django 3.2.4 on 2021-10-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattren', '0003_userlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presetlogos',
            name='printing_method',
        ),
        migrations.DeleteModel(
            name='PrintingMethod',
        ),
    ]
