# Generated by Django 3.2.4 on 2021-09-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pattren', '0003_userlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SublimationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Sublimation Category Name', max_length=250, unique=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresetSublimationPatterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Sublimation Name', max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='uploads/preset_logos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublimation_category', to='pattren.sublimationcategory')),
                ('printing_method', models.ManyToManyField(to='pattren.PrintingMethod')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
