# Generated by Django 3.2.4 on 2021-10-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattren', '0004_presetsublimationpatterns_sublimationcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presetlogos',
            name='printing_method',
        ),
    ]
