# Generated by Django 3.2.4 on 2021-11-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattren', '0005_remove_presetlogos_printing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetlogos',
            name='logo_price',
            field=models.IntegerField(default=0),
        ),
    ]
