# Generated by Django 3.2.4 on 2021-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattren', '0006_presetlogos_logo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetsublimationpatterns',
            name='logo_price',
            field=models.IntegerField(default=0),
        ),
    ]
