products_dict = [
    {'': {
        'front_view': 'false',
        'front_view_apron': 'false',
        'front_view_base_b_shirt': 'false',
        'front_view_base_b_jacket': 'false',
        'front_view_bomber_jac ': 'false',
        'front_view_coach_jac': 'false',
        'front_view_bag': 'false',
        'front_view_towel': 'false',
        'front_view_vest': 'false',
        'front_view_tank_top': 'false',
        'front_view_hat': 'false',
        'front_view_hoodie': 'false',
        'front_view_pant': 'false',

        'back_view': 'false',
        'back_view_base_b_shirt': 'false',
        'back_view_base_b_jacket': 'false',
        'back_view_base_bomber_jac': 'false',
        'back_view_base_coach_jac': 'false',
        'back_view_bag': 'false',
        'back_view_towel': 'false',
        'back_view_vest': 'false',
        'back_view_tank_top': 'false',
        'back_view_hat': 'false',
        'back_view_hoodie': 'false',
        'back_view_pant': 'false',

        'left_view': 'false',
        'left_view_base_b_shirt': 'false',
        'left_view_base_b_jacket': 'false',
        'left_view_bomber_jac': 'false',
        'left_view_coach_jac': 'false',
        'left_view_hat': 'false',
        'left_view_hoodie': 'false',

        'right_view': 'false',
        'right_view_base_b_shirt': 'false',
        'right_view_base_b_jacket': 'false',
        'right_view_bomber_jac': 'false',
        'right_view_coach_jac': 'false',
        'right_view_hat': 'false',
        'right_view_hoodie': 'false',
    }
        ,
        'shirt': {
            'front_view': 'true',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'true',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'true',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'true',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'vest': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'true',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'true',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'apron': {
            'front_view': 'false',
            'front_view_apron': 'true',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'bag': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'true',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'true',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'base-ball-jacket': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'true',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'true',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'true',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'true',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'base-ball-shirt': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'true',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'true',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'true',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'true',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'bomber-jacket': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'true',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'true',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'true',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'true',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'coach-jacket': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'true',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'true',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'true',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'true',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'hat': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'true',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'true',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'true',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'true',
            'right_view_hoodie': 'false',
        },

        'hoodie': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'true',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'true',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'true',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'true',
        },

        'pants': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'true',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'true',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'tank-top': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'false',
            'front_view_vest': 'false',
            'front_view_tank_top': 'true',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'false',
            'back_view_vest': 'false',
            'back_view_tank_top': 'true',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },

        'towel': {
            'front_view': 'false',
            'front_view_apron': 'false',
            'front_view_base_b_shirt': 'false',
            'front_view_base_b_jacket': 'false',
            'front_view_bomber_jac ': 'false',
            'front_view_coach_jac': 'false',
            'front_view_bag': 'false',
            'front_view_towel': 'true',
            'front_view_vest': 'false',
            'front_view_tank_top': 'false',
            'front_view_hat': 'false',
            'front_view_hoodie': 'false',
            'front_view_pant': 'false',

            'back_view': 'false',
            'back_view_base_b_shirt': 'false',
            'back_view_base_b_jacket': 'false',
            'back_view_base_bomber_jac': 'false',
            'back_view_base_coach_jac': 'false',
            'back_view_bag': 'false',
            'back_view_towel': 'true',
            'back_view_vest': 'false',
            'back_view_tank_top': 'false',
            'back_view_hat': 'false',
            'back_view_hoodie': 'false',
            'back_view_pant': 'false',

            'left_view': 'false',
            'left_view_base_b_shirt': 'false',
            'left_view_base_b_jacket': 'false',
            'left_view_bomber_jac': 'false',
            'left_view_coach_jac': 'false',
            'left_view_hat': 'false',
            'left_view_hoodie': 'false',

            'right_view': 'false',
            'right_view_base_b_shirt': 'false',
            'right_view_base_b_jacket': 'false',
            'right_view_bomber_jac': 'false',
            'right_view_coach_jac': 'false',
            'right_view_hat': 'false',
            'right_view_hoodie': 'false',
        },
    }
]

all_feilds = [
    {
        'front_view': 'false',
        'front_view_apron': 'false',
        'front_view_base_b_shirt': 'false',
        'front_view_base_b_jacket': 'false',
        'front_view_bomber_jac ': 'false',
        'front_view_coach_jac': 'false',
        'front_view_bag': 'false',
        'front_view_towel': 'false',
        'front_view_vest': 'false',
        'front_view_tank_top': 'false',
        'front_view_hat': 'false',
        'front_view_hoodie': 'false',
        'front_view_pant': 'false',

        'back_view': 'false',
        'back_view_base_b_shirt': 'false',
        'back_view_base_b_jacket': 'false',
        'back_view_base_bomber_jac': 'false',
        'back_view_base_coach_jac': 'false',
        'back_view_bag': 'false',
        'back_view_towel': 'false',
        'back_view_vest': 'false',
        'back_view_tank_top': 'false',
        'back_view_hat': 'false',
        'back_view_hoodie': 'false',
        'back_view_pant': 'false',

        'left_view': 'false',
        'left_view_base_b_shirt': 'false',
        'left_view_base_b_jacket': 'false',
        'left_view_bomber_jac': 'false',
        'left_view_coach_jac': 'false',
        'left_view_hat': 'false',
        'left_view_hoodie': 'false',

        'right_view': 'false',
        'right_view_base_b_shirt': 'false',
        'right_view_base_b_jacket': 'false',
        'right_view_bomber_jac': 'false',
        'right_view_coach_jac': 'false',
        'right_view_hat': 'false',
        'right_view_hoodie': 'false',
    }
]
