# Generated by Django 3.2.4 on 2021-06-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Body Name', max_length=250)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Product Category Name', max_length=250, unique=True)),
                ('key', models.CharField(help_text='Product Category Key', max_length=250, unique=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='ImageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Image Name', max_length=250)),
                ('image', models.ImageField(upload_to='uploads/body')),
                ('x_point', models.IntegerField()),
                ('y_point', models.IntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='ProductDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Product Category Name', max_length=250, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.category')),
                ('front_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.body')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.AddField(
            model_name='body',
            name='bottom_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_part', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='body',
            name='collar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='body',
            name='hem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hem', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='body',
            name='main_body_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_body_view', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='body',
            name='upper_chest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_chest', to='constructor.imagefield'),
        ),
    ]
