# Generated by Django 3.2.4 on 2021-06-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='bottom_part',
        ),
        migrations.RemoveField(
            model_name='body',
            name='main_body_view',
        ),
        migrations.RemoveField(
            model_name='body',
            name='upper_chest',
        ),
        migrations.AddField(
            model_name='body',
            name='body_first_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_first_section', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='body',
            name='body_second_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_second_section', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='body',
            name='body_third_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_third_section', to='constructor.imagefield'),
        ),
    ]
