# Generated by Django 3.2.4 on 2021-07-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdesign',
            old_name='back_view_base_bag',
            new_name='back_view_bag',
        ),
    ]
