# Generated by Django 3.2.4 on 2021-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_body_body_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdesign',
            name='display_image',
            field=models.ImageField(default=1, upload_to='uploads/display'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdesign',
            name='name',
            field=models.CharField(help_text='Product Design Name', max_length=250),
        ),
    ]
