# Generated by Django 3.2.4 on 2021-07-14 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_remove_body_body_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='body_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_view', to='constructor.imagefield'),
        ),
    ]
