# Generated by Django 3.2.4 on 2021-06-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_auto_20210611_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='left_sleeve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='l_sleeve', to='constructor.imagefield'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='body',
            name='right_sleeve',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='r_sleeve', to='constructor.imagefield'),
            preserve_default=False,
        ),
    ]
