# Generated by Django 3.2.4 on 2021-07-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_body_body_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='towelback',
            name='display_image',
            field=models.ImageField(default=1, upload_to='uploads/display'),
            preserve_default=False,
        ),
    ]
