# Generated by Django 3.2.4 on 2021-06-14 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_auto_20210613_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='collar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar', to='constructor.imagefield'),
        ),
        migrations.AlterField(
            model_name='body',
            name='hem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hem', to='constructor.imagefield'),
        ),
        migrations.AlterField(
            model_name='body',
            name='right_sleeve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_sleeve', to='constructor.imagefield'),
        ),
    ]
