# Generated by Django 3.2.4 on 2021-06-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_auto_20210614_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Right View', max_length=250)),
                ('right_v_lower_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_v_lower_part', to='constructor.imagefield')),
                ('right_v_upper_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_v_upper_part', to='constructor.imagefield')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='LeftView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Left View', max_length=250)),
                ('left_v_lower_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_v_lower_part', to='constructor.imagefield')),
                ('left_v_upper_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_v_upper_part', to='constructor.imagefield')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
            },
        ),
    ]
