# Generated by Django 3.2.4 on 2021-07-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_remove_apron_display_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apron',
            name='category',
        ),
    ]
