# Generated by Django 3.2.4 on 2021-06-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_leftview_rightview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdesign',
            name='left_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.leftview'),
        ),
        migrations.AddField(
            model_name='productdesign',
            name='right_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.rightview'),
        ),
    ]
