# Generated by Django 3.2.4 on 2021-06-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_auto_20210614_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftview',
            name='left_v_upper_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_v_upper_part', to='constructor.imagefield'),
        ),
    ]
