# Generated by Django 3.2.4 on 2021-06-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0010_backview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdesign',
            name='back_view',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.backview'),
            preserve_default=False,
        ),
    ]
