# Generated by Django 3.2.4 on 2021-08-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0011_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backview',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Shirt Back', 'verbose_name_plural': 'Shirt Back'},
        ),
        migrations.AlterModelOptions(
            name='baseballjacket_back',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Baseball Jacket Back', 'verbose_name_plural': 'Baseball Jacket Back'},
        ),
        migrations.AlterModelOptions(
            name='baseballjacket_front',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Baseball Jacket Front', 'verbose_name_plural': 'Baseball Jacket Front'},
        ),
        migrations.AlterModelOptions(
            name='baseballjacket_left',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Baseball Jacket Left', 'verbose_name_plural': 'Baseball Jacket Left'},
        ),
        migrations.AlterModelOptions(
            name='baseballjacket_right',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Baseball Jacket Rightt', 'verbose_name_plural': 'Baseball Jacket Right'},
        ),
        migrations.AlterModelOptions(
            name='baseballshirt_back',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Baseball Shirt Back', 'verbose_name_plural': 'Baseball Shirt Back'},
        ),
        migrations.AlterModelOptions(
            name='baseballshirt_front',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Baseball Shirt Front', 'verbose_name_plural': 'Baseball Shirt Front'},
        ),
        migrations.AlterModelOptions(
            name='baseballshirt_left',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Baseball Shirt Left', 'verbose_name_plural': 'Baseball Shirt Left'},
        ),
        migrations.AlterModelOptions(
            name='baseballshirt_right',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Baseball Shirt Right', 'verbose_name_plural': 'Baseball Shirt Right'},
        ),
        migrations.AlterModelOptions(
            name='body',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Front Shirt', 'verbose_name_plural': 'Front Shirt'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='designimages',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Graphics for Customer', 'verbose_name_plural': 'Graphics for Customer'},
        ),
        migrations.AlterModelOptions(
            name='leftview',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Shirt Left', 'verbose_name_plural': 'Shirt Left'},
        ),
        migrations.AlterModelOptions(
            name='rightview',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Shirt Right', 'verbose_name_plural': 'Shirt Right'},
        ),
    ]
