# Generated by Django 3.2.4 on 2021-06-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0011_productdesign_back_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='backview',
            name='back_left_sleeve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_left_sleeve', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='backview',
            name='back_right_sleeve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_right_sleeve', to='constructor.imagefield'),
        ),
    ]
