# Generated by Django 3.2.4 on 2021-06-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0012_auto_20210615_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftview',
            name='left_v_body_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_v_body_view', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='rightview',
            name='right_v_body_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_v_body_view', to='constructor.imagefield'),
        ),
    ]
