# Generated by Django 3.2.4 on 2021-08-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0013_auto_20210825_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdesign',
            name='fabrics',
            field=models.ManyToManyField(to='constructor.Fabric'),
        ),
    ]
