# Generated by Django 3.2.4 on 2021-07-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0015_auto_20210702_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='left_sleeve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l_sleeve', to='constructor.imagefield'),
        ),
    ]
