# Generated by Django 3.2.4 on 2021-10-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0015_auto_20211011_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Component Name', max_length=250)),
                ('display_image', models.ImageField(upload_to='uploads/display')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.category')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productdesign',
            name='component_selected',
            field=models.ManyToManyField(to='constructor.ComponentSelection'),
        ),
    ]
