# Generated by Django 3.2.4 on 2021-07-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0017_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftview',
            name='left_v_left_s_lower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_v_left_s_lower', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='leftview',
            name='left_v_left_s_upper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_v_left_s_upper', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='leftview',
            name='left_v_right_s_lower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_v_right_s_lower', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='leftview',
            name='left_v_right_s_upper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_v_right_s_upper', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='rightview',
            name='right_v_left_s_lower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_v_left_s_lower', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='rightview',
            name='right_v_left_s_upper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_v_left_s_upper', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='rightview',
            name='right_v_right_s_lower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_v_right_s_lower', to='constructor.imagefield'),
        ),
        migrations.AddField(
            model_name='rightview',
            name='right_v_right_s_upper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_v_right_s_upper', to='constructor.imagefield'),
        ),
    ]
