# Generated by Django 3.2.4 on 2021-11-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0017_auto_20211018_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentselection',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
