# Generated by Django 3.2.4 on 2021-11-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0018_componentselection_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdesign',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
    ]
