# Generated by Django 3.2.4 on 2021-11-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0019_productdesign_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdesign',
            name='component_selected',
            field=models.ManyToManyField(blank=True, null=True, to='constructor.ComponentSelection'),
        ),
    ]
