# Generated by Django 3.2.4 on 2021-07-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0019_towel'),
    ]

    operations = [
        migrations.AddField(
            model_name='towel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.category'),
            preserve_default=False,
        ),
    ]
