# Generated by Django 3.2.4 on 2021-11-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0020_alter_productdesign_component_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingmethod',
            name='digital_sizes_cost',
            field=models.ManyToManyField(blank=True, null=True, to='constructor.DigitalPrintingMethodSizeCostQuantity'),
        ),
        migrations.AlterField(
            model_name='printingmethod',
            name='silk_sizes_quantity_cost',
            field=models.ManyToManyField(blank=True, null=True, to='constructor.SilkPrintingMethodSizeCostQuantity'),
        ),
    ]
