# Generated by Django 3.2.4 on 2021-11-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0021_auto_20211105_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingmethod',
            name='printing_price',
            field=models.IntegerField(default=0),
        ),
    ]
