# Generated by Django 3.2.4 on 2021-07-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0021_apron'),
    ]

    operations = [
        migrations.AddField(
            model_name='apron',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='constructor.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apron',
            name='body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='body', to='constructor.imagefield'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apron',
            name='collar_strip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='collar_strip', to='constructor.imagefield'),
            preserve_default=False,
        ),
    ]
