# Generated by Django 3.2.4 on 2021-11-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0022_printingmethod_printing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silkprintingmethodsizecostquantity',
            old_name='custom_cost',
            new_name='additional_color_cost',
        ),
        migrations.RenameField(
            model_name='silkprintingmethodsizecostquantity',
            old_name='standard_cost',
            new_name='first_color_cost',
        ),
        migrations.AddField(
            model_name='silkprintingmethodsizecostquantity',
            name='color_type',
            field=models.CharField(choices=[('solid_color', 'Solid Color'), ('silver', 'Silver'), ('gold', 'Gold')], default='solid_color', max_length=50),
        ),
        migrations.AddField(
            model_name='silkprintingmethodsizecostquantity',
            name='screen_cost',
            field=models.FloatField(default=0),
        ),
    ]
