# Generated by Django 3.2.4 on 2021-11-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0023_auto_20211111_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingmethod',
            name='printing_method',
            field=models.CharField(choices=[('silk_screen', 'Silk Screen Printing'), ('heat_transfer', 'Heat Transfer Printing'), ('digital', 'Digital Printing')], default='silk_screen', max_length=50, unique=True),
        ),
    ]
