# Generated by Django 3.2.4 on 2021-07-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0023_auto_20210708_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='VestFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='VestFront', max_length=250)),
                ('collar_vest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_vest', to='constructor.imagefield')),
                ('vest_bottom_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_bottom_left', to='constructor.imagefield')),
                ('vest_bottom_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_bottom_right', to='constructor.imagefield')),
                ('vest_hem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_hem', to='constructor.imagefield')),
                ('vest_left_sleeve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_left_sleeve', to='constructor.imagefield')),
                ('vest_mid_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_mid_left', to='constructor.imagefield')),
                ('vest_mid_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_mid_right', to='constructor.imagefield')),
                ('vest_pocket_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_pocket_left', to='constructor.imagefield')),
                ('vest_pocket_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_pocket_right', to='constructor.imagefield')),
                ('vest_right_sleeve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_right_sleeve', to='constructor.imagefield')),
                ('vest_top_full', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_top_full', to='constructor.imagefield')),
                ('vest_top_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_top_left', to='constructor.imagefield')),
                ('vest_top_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_top_right', to='constructor.imagefield')),
                ('zip_vest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip_vest', to='constructor.imagefield')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='VestBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='VestBack', max_length=250)),
                ('collar_vest_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_vest_back', to='constructor.imagefield')),
                ('vest_bottom_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_bottom_back', to='constructor.imagefield')),
                ('vest_full_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_full_back', to='constructor.imagefield')),
                ('vest_hem_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_hem_back', to='constructor.imagefield')),
                ('vest_left_sleeve_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_left_sleeve_back', to='constructor.imagefield')),
                ('vest_mid_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_mid_back', to='constructor.imagefield')),
                ('vest_pocket_left_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_pocket_left_back', to='constructor.imagefield')),
                ('vest_pocket_right_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_pocket_right_back', to='constructor.imagefield')),
                ('vest_right_sleeve_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_right_sleeve_back', to='constructor.imagefield')),
                ('vest_top_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest_top_back', to='constructor.imagefield')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
            },
        ),
    ]
