# Generated by Django 3.2.4 on 2021-11-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0024_alter_printingmethod_printing_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printingmethod',
            old_name='printing_price',
            new_name='printing_base_price',
        ),
        migrations.RemoveField(
            model_name='printingmethod',
            name='heat_transfer_sizes_cost',
        ),
        migrations.AddField(
            model_name='printingmethod',
            name='heat_transfer_sizes_cost',
            field=models.ManyToManyField(blank=True, null=True, to='constructor.HeatTransferPrintingMethodSizeCostQuantity'),
        ),
    ]
