# Generated by Django 3.2.4 on 2021-11-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0025_auto_20211111_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattransferprintingmethodsizecostquantity',
            name='name',
            field=models.CharField(default='test', help_text='Name', max_length=250),
            preserve_default=False,
        ),
    ]
