# Generated by Django 3.2.4 on 2021-11-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0026_heattransferprintingmethodsizecostquantity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattransferprintingmethodsizecostquantity',
            name='printing_type',
            field=models.CharField(choices=[('color_printing', 'Color Printing'), ('3m_reflective', '3M Reflective'), ('metal', 'Metal')], max_length=50),
        ),
    ]
