# Generated by Django 3.2.4 on 2021-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0027_alter_heattransferprintingmethodsizecostquantity_printing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalprintingmethodsizecostquantity',
            name='name',
            field=models.CharField(default='test', help_text='Name', max_length=250),
            preserve_default=False,
        ),
    ]
