# Generated by Django 3.2.4 on 2021-07-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0028_remove_productdesign_front_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdesign',
            name='front_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.apron'),
        ),
        migrations.AddField(
            model_name='productdesign',
            name='front_view_shirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.body'),
        ),
        migrations.AlterField(
            model_name='productdesign',
            name='back_view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.backview'),
        ),
    ]
