# Generated by Django 3.2.4 on 2021-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0030_auto_20211125_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
