# Generated by Django 3.2.4 on 2022-01-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0031_userorder_payment_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='userorder',
            name='hundred',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='l',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='oneForty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='threeXl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='total_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userorder',
            name='xs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
